### ISSUE TITLE
Forcings at top level

### ISSUE THREAD

**Issue by eguil** [ES-DOC/cmip6-specializations-toplevel#6]
David is to ask Tim Johns @UKMO if the Table 12.1 properties depend on the experiment or not. If not, the forcing properties could be collected via a process at the model top level.

**Comment by davidhassell** [comment]
**A summary of recent e-mails on this topic (latest first):** (I'm stalled, I think, waiting for thoughts on my question in the most recent message) 

David Hassell david.hassell@ncas.ac.uk

16 Sep (4 days ago)

to Mark, Eric.Guilyardi, Tim

Hi Mark, et al.

For me, the question might be, for a given forcing (e.g. CH4), "does the table record solely that the physical process is explicitly represented in the model, or does it also include the  possibility that the forcing is provided by some (any) other means (e.g. by equivalent CO2, etc.)".

Tim's points are already very useful (particulary about it only applying to concentration and emission driven projection simulations).

Thanks,

David

On 16 September 2016 at 10:40, Elkington, Mark mark.elkington@metoffice.gov.uk wrote:

```
Hi Eric

I must be mis-understanding something.  How can the forcing be part of the model properties   
when a model can have different forcings applied depending on the experiment involved? – or are 
you talking about defining “how” a forcing is applied within the model in the model properties and 
“what” specific forcing data is applied in the conformance information we will generate.

Mark
```

Johns, Tim

16 Sep (4 days ago)

to Eric.Guilyardi, me, Mark

Hi Eric and David,   cc: Mark

This sounds like a laudable aim for CMIP6, at least to make substantial progress towards automating the metadata gathering in order to build tables such as 12.1 and the complementary mammoth Tables in Chapter 9 with slightly less human effort.

Speaking for Table 12.1 I found it a painstaking and difficult task to gather this information with a simple protocol, given the variations in forcing implementations in different models. In terms of scope Table 12.1 relates only to models used for 'concentrations-driven' and 'emissions-driven' projection simulations, including historical. That’s only a subset of the total CMIP5 entry as some models only ran idealised expts I think, and Table12.1 also doesn’t cover EMICs (Table 9.A.2).

Not sure I can answer the question posed by David of whether or not the details in table 12.1 are independent of the MIP experiments (as regards CMIP5) therefore. Even  the CMIP5 protocol was of broader scope than my remit in compiling this Table. CMIP6 looks even more complex in that respect and I suspect you face a big challenge  in compiling the metadata protocol (particularly up front before the groups have necessarily worked out the finer details of how they will implement experiments) in such a way as to categorise all possible variants of forcing implementations (and other things about the experiment implementations too I guess). One reason that I say this is that the way that I asked the questions of CMIP5 modelling groups and then mapped it into the eventual Table evolved over time through the IPCC drafting process. This was in response both to the way that groups described the complexity of variations in how they had interpreted and implemented the forcings, partly in response to the evolving assessment needs (e.g. new terminology for cloud-radiation-aerosol forcings, sub-classes of AOGCMs and ESMs), and partly from in-chapter and cross-chapter coordination discussions. A significant effort was involved (not just by me, also by the modelling groups) in elucidating things to ensure that information was correctly translated into the Table such that significant relevant features were captured that would allow analysts to understand results from different models in context. A number of quality-control loops were involved in the Table iteration process therefore.

That is not to discourage you from the tasks ahead though, and hopefully there are some lessons to learn from the CMIP5 experience and material to build on. I have archived over 1000 emails from my IPCC Chapter 12 forcing work, quite a large portion of which relate to Table 12.1, but maybe a useful starting point would be if I send you copies of some of key emails that I sent around the CMIP5 groups asking for the forcing information. (I also have a working excel sheet I think that might be of interest.) That would hopefully give you an idea of how the questions were posed/answered and how it evolved over time, which might help to inform your approach in automating this for CMIP6 (e.g. separating the order-1 questions that can be asked up front and the order-2 details that can only be answered after experiments are run). Let me know if this would be useful and if so I’ll dig out some of the most relevant stuff.

Just for clarification, I’m now working in Foundation Science rather than Climate Science here at the Met Office and don’t have direct involvement in CMIP6 activities other than contributing to the development of the underpinning physical coupled model (HadGEM3-GC3). But I do still take a scientific interest in what’s happening of course!

Best wishes,

Tim

```
From: Eric Guilyardi [mailto:eric.guilyardi@ncas.ac.uk]
Sent: 16 September 2016 09:45
To: David Hassell; Johns, Tim; Elkington, Mark
Subject: Re: Radiative forcing agents in the CMIP6



Dear Tim, (I add Mark in cc in case you need to discuss more of the ES-DOC details with him)

Further to David's email, it came as a WGCM use case that we collect this forcing information in a more automated way (recollecting your heroic efforts !). The key is to know if this forcing information can be collected before the experiments are run, i.e while modelling groups are documenting their model realms, or if it is experiment-dependent, which would then require to collect this after the experiment are run. In the - much simpler ! - first case, we would then add the forcing information at the top level model properties.

Thank you for your key inputs,

Eric

PS: you can view the current CMIP6 MIP protocols from http://search.es-doc.org



On 16/9/16 10:07, David Hassell wrote:

    Dear Tim (cc Eric),

    I hope you are well, and your CMIP6 preparations are going to plan!

    We (at ES-DOC) are trying to work out the best way to automatically generate, from the metadata that we are collecting from the modelling groups, the CMIP6 version of the IPCC AR5 table 12.1 - "Radiative forcing agents in the CMIP5 multi-model global climate projections" (attached for reference). As I understand it, for AR5, this table was compiled manually with  a lot of research and personal communication, and it will be a great benefit to collate this information in a more rigorous fashion.

    To help us collect this forcing information, it would be very useful to know your advice on the question of whether or not the details in table 12.1 are independent of the MIP experiments - i.e. do any of the table entries for a given model depend on the MIP experiment being run or they the same across all experiments?

    I look forward to hearing your thoughts on this,
    Many thanks and all the best,

    David
```

**Comment by charliepascoe** [comment]
My response to Tim et al:

Thanks for sharing your thoughts Tim.

I’m working on interpreting the documentation that has been produced by (and on behalf of) the CMIP6 MIP teams in terms of teasing out the forcing requirements for each of the CMIP6 experiments.

I certainly recognise your distinction between forcings that can be answered up-front (order_1) and those that can only be known after an experiment has been run (order_2) in the work that I’ve been doing.  I think it would be worthwhile to capture that information in our ES-Doc metadata.

I don’t think it makes sense to label forcings as either generic (applied equally to all experiments) or specific (applicable to a unique experiment) as has been suggested by Eric, the reality for CMIP6 is more complicated than that.  But we could categorise forcings in terms of how widely they are shared, in which case I see four levels of forcing:
1.  shared widely across CMIP6 e.g. "concentration of pre-industrial CO2" & "Impose AMIP SSTs".
2.  shared with companion MIPs e.g. aerosol forcing in GeoMIP and AerChemMIP.
3.  shared within a MIP e.g. spin-up protocol for land surface experiments in LUMIP.
4.  is applied to a single experiment e.g. CFMIP "zonally uniform SST plus 4K"

I don't think we can know, a-priori, whether modelling groups will implement a forcing in the same way across all the experiments that use it.   I expect that we will need to look to the conformance information rather than the model descriptions to produce a table like that of 12.1 in the WGI AR5.  That said, because we know how widely each forcing is shared across the CMIP6 experiments, we will be able to broaden the scope of a 12.1-like table beyond that of the historical and scenario forcing experiments represented in AR5.

**Comment by eguil** [comment]
Summary of todays' telco discussion:
1) Table 12.1 properties will be asked at the top level- they are mostly independant from numerical requirements
2) Conformance to num. req. of experiments will be delt with separately (and most likely after simulations are run), using the 4 scopes defined by Charlotte. These 4 lists can be provided upfront and groups can either organise themselves per experiment/model pair (but with some amount of repeat) or per scope/model pair with a process (to be developed) to rebuilt the conformance doc per experiment/model pair

**Comment by eguil** [comment]
First draft ready for review
